/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiExtensionAuthRouteImport } from './routes/api/extension/auth'
import { Route as ApiExtensionCapturesRouteImport } from './routes/api/extension/captures'
import { Route as ApiExtensionDedupeRouteImport } from './routes/api/extension/dedupe'
import { Route as ApiExtensionFoldersRouteImport } from './routes/api/extension/folders'
import { Route as ApiMediaFileIdRouteImport } from './routes/api/media/$fileId'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionAuthRoute = ApiExtensionAuthRouteImport.update({
  id: '/api/extension/auth',
  path: '/api/extension/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionCapturesRoute = ApiExtensionCapturesRouteImport.update({
  id: '/api/extension/captures',
  path: '/api/extension/captures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionDedupeRoute = ApiExtensionDedupeRouteImport.update({
  id: '/api/extension/dedupe',
  path: '/api/extension/dedupe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionFoldersRoute = ApiExtensionFoldersRouteImport.update({
  id: '/api/extension/folders',
  path: '/api/extension/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaFileIdRoute = ApiMediaFileIdRouteImport.update({
  id: '/api/media/$fileId',
  path: '/api/media/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/captures': typeof ApiExtensionCapturesRoute
  '/api/extension/dedupe': typeof ApiExtensionDedupeRoute
  '/api/extension/folders': typeof ApiExtensionFoldersRoute
  '/api/media/$fileId': typeof ApiMediaFileIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/captures': typeof ApiExtensionCapturesRoute
  '/api/extension/dedupe': typeof ApiExtensionDedupeRoute
  '/api/extension/folders': typeof ApiExtensionFoldersRoute
  '/api/media/$fileId': typeof ApiMediaFileIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/auth': typeof ApiExtensionAuthRoute
  '/api/extension/captures': typeof ApiExtensionCapturesRoute
  '/api/extension/dedupe': typeof ApiExtensionDedupeRoute
  '/api/extension/folders': typeof ApiExtensionFoldersRoute
  '/api/media/$fileId': typeof ApiMediaFileIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/uploads'
    | '/api/auth/google'
    | '/api/extension/auth'
    | '/api/extension/captures'
    | '/api/extension/dedupe'
    | '/api/extension/folders'
    | '/api/media/$fileId'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/uploads'
    | '/api/auth/google'
    | '/api/extension/auth'
    | '/api/extension/captures'
    | '/api/extension/dedupe'
    | '/api/extension/folders'
    | '/api/media/$fileId'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/api/uploads'
    | '/api/auth/google'
    | '/api/extension/auth'
    | '/api/extension/captures'
    | '/api/extension/dedupe'
    | '/api/extension/folders'
    | '/api/media/$fileId'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiExtensionAuthRoute: typeof ApiExtensionAuthRoute
  ApiExtensionCapturesRoute: typeof ApiExtensionCapturesRoute
  ApiExtensionDedupeRoute: typeof ApiExtensionDedupeRoute
  ApiExtensionFoldersRoute: typeof ApiExtensionFoldersRoute
  ApiMediaFileIdRoute: typeof ApiMediaFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/auth': {
      id: '/api/extension/auth'
      path: '/api/extension/auth'
      fullPath: '/api/extension/auth'
      preLoaderRoute: typeof ApiExtensionAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/captures': {
      id: '/api/extension/captures'
      path: '/api/extension/captures'
      fullPath: '/api/extension/captures'
      preLoaderRoute: typeof ApiExtensionCapturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/dedupe': {
      id: '/api/extension/dedupe'
      path: '/api/extension/dedupe'
      fullPath: '/api/extension/dedupe'
      preLoaderRoute: typeof ApiExtensionDedupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/folders': {
      id: '/api/extension/folders'
      path: '/api/extension/folders'
      fullPath: '/api/extension/folders'
      preLoaderRoute: typeof ApiExtensionFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$fileId': {
      id: '/api/media/$fileId'
      path: '/api/media/$fileId'
      fullPath: '/api/media/$fileId'
      preLoaderRoute: typeof ApiMediaFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiExtensionAuthRoute: ApiExtensionAuthRoute,
  ApiExtensionCapturesRoute: ApiExtensionCapturesRoute,
  ApiExtensionDedupeRoute: ApiExtensionDedupeRoute,
  ApiExtensionFoldersRoute: ApiExtensionFoldersRoute,
  ApiMediaFileIdRoute: ApiMediaFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
