"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from "boneyard-js/react"

import _library_shell from "./library-shell.bones.json"

registerBones({
  "library-shell": _library_shell,
})
